### ISSUE TITLE
pod is bad as it has unversioned dependency that just changed and breaks xcode7 support

### ISSUE THREAD

**Issue by Daij-Djan** [anilgoktas/ReachabilityStatus#1]
pod is bad as it has unversioned dependency that just changed and breaks xcode7 support

**Comment by anilgoktas** [comment]
I'm aware of xcode7-8 support breaks. Will take a closer look on the few next days.

0.1.4 should work with xcode8 & swift 3.0

**Comment by anilgoktas** [comment]
Since it's not a crucial pod, I'm not planning on supporting old versions of Xcode and Swift.

Latest version (2.0) is now currently supporting Swift 3
